# Metrics
AllCops:
  TargetRubyVersion: 2.4

Layout/HashAlignment:
  Include:
    - 'lib/**/*.rb'
Layout/LineLength:
  Include:
    - 'lib/**/*.rb'
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockNesting:
  Exclude:
    - 'bin/*'
Metrics/MethodLength:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 10
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
